/* Automatically generated by configure */
#ifndef GF_CONFIG_H
#define GF_CONFIG_H
#define GPAC_CONFIGURATION "--prefix=/home/komisar/x264/lib/32 --strip --disable-ipv6 --disable-wx --disable-oss-audio --disable-x11-shm --disable-x11-xv --disable-sdl --disable-ssl --disable-opengl --disable-directx --static-mp4box --enable-static --disable-shared --target-os=mingw32 --cpu=i686 --extra-cflags='-O3 -pipe -fomit-frame-pointer -mfpmath=sse -msse  -march=pentium3 -mtune=generic -floop-interchange -floop-strip-mine -floop-block -ffast-math -DNDEBUG' --extra-cppflags='-O3 -pipe -fomit-frame-pointer -mfpmath=sse -msse  -march=pentium3 -mtune=generic -floop-interchange -floop-strip-mine -floop-block -ffast-math -DNDEBUG' --extra-ldflags='-s ' --cc=gcc --cpp=g++"
#define GPAC_CONFIG_WIN32
#define GPAC_DISABLE_3D
#endif
