#ifndef __EASYDARWIN_RESOURCES_H__
#define __EASYDARWIN_RESOURCES_H__

#define EASY_DARWIN_REDIS_EASYCMS				"EasyCMS"
#define EASY_DARWIN_REDIS_EASYDARWIN			"EasyDarwin"
#define EASY_DARWIN_REDIS_DEVICE				"Device"
#define EASY_DARWIN_REDIS_LIVE					"Live"

#define EASY_DARWIN_REDIS_IP					"IP"
#define EASY_DARWIN_REDIS_PORT					"Port"
#define EASY_DARWIN_REDIS_LOAD					"Load"

#define EASY_DARWIN_REDIS_HTTP					"HTTP"
#define EASY_DARWIN_REDIS_RTSP					"RTSP"

#define EASY_DARWIN_REDIS_TYPE					"Type"
#define EASY_DARWIN_REDIS_CHANNEL				"Channel"
#define EASY_DARWIN_REDIS_TOKEN					"Token"

#define EASY_DARWIN_REDIS_BITRATE				"Bitrate"
#define EASY_DARWIN_REDIS_OUTPUT				"Output"

#endif //__EASYDARWIN_RESOURCES_H__

