.Dd February 11, 2005       \" DATE 
.Dt streamingadminserver.pl 8       \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm streamingadminserver.pl 
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
is a web server that manages the html for QuickTimeStreamingServer web-based administration.
.Pp
.Sh SEE ALSO 
.Xr QuickTimeStreamingServer 8 , 
.\" .Sh BUGS 
.\" .Sh HISTORY 