.Dd February 11, 2005       \" DATE 
.Dt StreamingLoadTool 8       \" Program name and manual section number 
.Os Darwin
.Sh NAME                 \" Section Header - required - don't modify 
.Nm StreamingLoadTool 
.Nd Load testing tool for QuickTimeStreamingServer
.Sh SYNOPSIS             \" Section Header - required - don't modify
.Nm
.Op Fl d              \" [-d]
.Op Fl i Ar urlid         \" [-i urlid] 
.Op Fl f Ar path         \" [-f configFile] 
.Op Fl c Ar #         \" [-c #]
-c fileName                 
.Sh DESCRIPTION          \" Section Header - required - don't modify
.Nm
simulates multiple RTSP/RTP clients.  The number of clients, URLs, and other 
options can be configured via a 
.Ar configFile .
.Pp
A list of flags and their descriptions:
.Bl -tag -width -indent  \" Differs from above in -compact tag removed
.It Fl f Ar configFile
Config file to use. The default is /Library/QuickTimeStreaming/Config/streamingloadtool.conf
.It Fl c Ar httpCookie
HTTP cookie to use. Overrides what is in config file
.It Fl i Ar urlID
RTSP stream URL id (i.e. trackID or streamID etc.). Default is -i trackID
.It Fl d
Display debug messages
.El
.Sh FILES
.Bl -tag -width /Library/QuickTimeStreaming/Config/streamingloadtool.conf -compact
.It Pa /Library/QuickTimeStreaming/Config/streamingloadtool.conf
.El
.Sh SEE ALSO 
.Xr QuickTimeStreamingServer 8 , 
.\" .Sh BUGS 
.\" .Sh HISTORY 