#!/bin/sh
 
cd ../CommonUtilitiesLib
if [ "$*" = "clean" ] ; then
    make -f nbproject/Makefile-ARM.mk QMAKE= SUBPROJECTS= .clean-conf	
	make -f nbproject/Makefile-Release.mk QMAKE= SUBPROJECTS= .clean-conf
elif [ "$*" = "arm" ] ; then
    make -f nbproject/Makefile-ARM.mk QMAKE= SUBPROJECTS= .build-conf
else 
	make -f nbproject/Makefile-Release.mk QMAKE= SUBPROJECTS= .build-conf
fi

cd ../EasyDarwin
if [ "$*" = "clean" ] ; then
    make -f nbproject/Makefile-ARM.mk QMAKE= SUBPROJECTS= .clean-conf	
	make -f nbproject/Makefile-Release.mk QMAKE= SUBPROJECTS= .clean-conf
elif [ "$*" = "arm" ] ; then
    make -f nbproject/Makefile-ARM.mk QMAKE= SUBPROJECTS= .build-conf
else 
	make -f nbproject/Makefile-Release.mk QMAKE= SUBPROJECTS= .build-conf
fi
