#!/bin/sh
 
rm -rf EasyDarwinDeploy/ EasyDarwinDeploy.tar
echo "create deploy directory"
mkdir -p EasyDarwinDeploy/Movies

echo "copy necessary files"
if [ -f EasyDarwin ]; then
	cp -v EasyDarwin easydarwin.xml WinNTSupport/devices.xml EasyDarwinDeploy/
	cp -v Demo.mp4 EasyDarwinDeploy/Movies	
	echo "generate tarball"
	tar cvf EasyDarwinDeploy.tar EasyDarwinDeploy/
	echo Success!
else
	echo Build EasyDarwin failed!
fi
