#ifndef _CLIENT_SYSTEM_COMMON_DEF_H
#define _CLIENT_SYSTEM_COMMON_DEF_H

//系统消息
#define SYSTEM_MSG_NET_MESSAGE		  0X01000000
#define SYSTEM_MSG_CREATE_SESSION     0X01000001
#define SYSTEM_MSG_LOGIN    		  0X01000002
#define SYSTEM_MSG_QUERY_DEVICE_LIST  0X01000003
#define SYSTEM_MSG_QUERY_DEVICE_INFO  0X01000004
#define SYSTEM_MSG_HEARTBEAT          0X01000005
#define SYSTEM_MSG_ERROR			  0X01000006
#define SYSTEM_MSG_PUBLISH_STREAM	  0X01000007
#define SYSTEM_MSG_SNAP_UPDATE_REQ	  0X01000008

//网络消息结构体
typedef void* COMMON_SOCKET_HANDLE;
typedef void* COMMON_HANDLE;

enum ClientMsgType
{
	CLIENT_ERROR = 0,
	CLIENT_MSG_REGISTER_USER,
	CLIENT_MSG_LOGIN,
	CLIENT_MSG_HEARTBEAT,
	CLIENT_MSG_GET_DEVICE_LIST,
	CLIENT_MSG_GET_DEVICE_INFO,
	CLIENT_MSG_GET_USER_INFO,
	CLIENT_MSG_PUBLISH_STREAM,
	CLIENT_MSG_PUBLISH_STREAM_START
};

typedef unsigned int u32;
typedef unsigned long long u64;

#endif
